# YAML config file


hv_consep_class:
  
  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: True
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  stain_norm: 
   norm_brightness: True
   mode: 'train'
   image: 'train_1'

  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_consep/data/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'test'
  step_size: [80, 80]
  win_size: [540, 540]
  
  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types: 
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle: 4
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_standard'
  train_dir: 
    - 'train/Annotations'
    # '/data/output/extract/hv_consep_seg_class_540x540_80x80_stain_norm/train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4
  
  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: False
  inf_model: 'hv_class_consep.npz'
  # inf_imgs_ext: '.png'
  inf_data_list: 
    - 'test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''


hv_consep_class_linear_uit_20:
  
  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: True
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  stain_norm: 
   norm_brightness: True
   mode: 'train'
   image: 'train_1'

  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_consep/data/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'test'
  step_size: [80, 80]
  win_size: [540, 540]
  
  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types: 
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle: 4
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_linear'
  train_dir: 
    - 'train/Annotations'
    # '/data/output/extract/hv_consep_seg_class_540x540_80x80_stain_norm/train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4
  
  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: True
  inf_model: 'hv_class_consep.npz'
  # inf_imgs_ext: '.png'
  inf_data_list: 
    - 'data_uit_20/test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''


hv_pannuke_class:
  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv_opt'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: False
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  # stain_norm:
  #  norm_brightness: True
  #  mode: 'train'
  #  image: 'train_1'


  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_pannuke/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'valid'
    - 'test'
  step_size: [164, 164]
  win_size: [256, 256] 

  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types:
    Inflammatory: 1
    Connective: 2
    Dead cells: 3
    Epithelial: 4
    Neoplastic cells: 5
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_standard'
  train_dir: 
    - 'train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4

  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: False
  inf_model: 'hv_class_pannuke.npz'
  # inf_imgs_ext: '.png'
  inf_data_list:
    - 'test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''


hv_pannuke_class_linear_uit_20:
  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv_opt'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: False
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  # stain_norm:
  #  norm_brightness: True
  #  mode: 'train'
  #  image: 'train_1'

  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_pannuke/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'valid'
    - 'test'
  step_size: [164, 164]
  win_size: [256, 256] 

  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types:
    Inflammatory: 1
    Connective: 2
    Dead cells: 3
    Epithelial: 4
    Neoplastic cells: 5
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_linear'
  train_dir: 
    - 'train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4

  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: True
  inf_model: 'hv_class_pannuke.npz'
  # inf_imgs_ext: '.png'
  inf_data_list:
    - 'data_uit_20/test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''

hv_consep_class_linear_pannuke_data:
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv_opt'

hv_pannuke_class_linear_consep_data:
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv_opt'

################################
################################
################################

hv_consep_class_linear_uit_1202:

  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: True
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  stain_norm: 
    norm_brightness: True
    mode: 'train'
    image: 'train_1'

  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_consep/data/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'test'
  step_size: [80, 80]
  win_size: [540, 540]
  
  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types: 
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle: 4
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_linear'
  train_dir: 
    - 'train/Annotations'
    # '/data/output/extract/hv_consep_seg_class_540x540_80x80_stain_norm/train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4
  
  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: True
  inf_model: 'hv_class_consep.npz'
  # inf_imgs_ext: '.png'
  inf_data_list: 
    - 'data_uit_1202/test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''

  
hv_pannuke_class_linear_uit_1202:
  ###
  # Meta information about profile pipeline
  ###  
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv_opt'
  input_prefix: '/data/input/'
  output_prefix: '/data/output/'

  ###
  # Choosing optional steps 
  ###
  include_preproc: False
  include_extract: True
  include_export: True
  
  ###
  # Normaliztion or preprocessing step
  ###
  # stain_norm:
  #  norm_brightness: True
  #  mode: 'train'
  #  image: 'train_1'

  ###
  # Extraction step
  # assume that patches have png format
  ###
  data_dir: 'data_pannuke/'
  extract_type: 'mirror'
  # img_ext: '.png'
  data_modes:
    - 'train'
    - 'valid'
    - 'test'
  step_size: [164, 164]
  win_size: [256, 256] 

  ###
  # Train step
  # Number of types - len(nuclei_types.values()) + 1, 0 is background
  # Data type - .npy
  # Augmentations ...
  # Train directory have format <prefix/dataset/train/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Valid directory have format <prefix/dataset/valid/Annotations>, note that it SHOULD be <R|G|B|instance|type> and of the right size
  # Train procs - 8, valid procs - 4 by default
  ###
  seed: 10
  type_classification: True
  nuclei_types:
    Inflammatory: 1
    Connective: 2
    Dead cells: 3
    Epithelial: 4
    Neoplastic cells: 5
  # data_ext: '.npy'
  input_norm: True
  input_augs: 'p_linear'
  train_dir: 
    - 'train/Annotations'
  valid_dir: 
    - 'test/Annotations'
  # nr_procs_train: 8
  # nr_procs_valid: 4

  ###
  # Inference step
  # Model path have format <input_prefix/models/name>, if inf_auto_find_chkpt = True - use save_dir from training
  # Input images path have format <input_prefix/path>
  # Images are .png by default
  ###
  inf_auto_find_chkpt: True
  inf_model: 'hv_class_pannuke.npz'
  # inf_imgs_ext: '.png'
  inf_data_list:
    - 'data_uit_1202/test/Images'

  ###
  # Process step
  # Remap labels used for optimizing analysis later on
  # Outline expects name of the type of nuclei, that are in nuclei_types dict
  ###
  remap_labels: True
  outline: ''

################################