# YAML config file

##################################
#########Default profiles#########
##################################

hv_seg_class_consep:
  exp_id: '1.0'
  mode: 'hover'
  model_type: 'np_hv'

  extract_data_dir: '/pfs/input/'
  extract_type: 'mirror'
  img_ext: '.png'
  data_modes:
    - 'train'
    - 'test'
  step_size: [80, 80]
  win_size: [540, 540]

  seed: 10
  type_classification: True
  nr_types: 5 
  nuclei_types: 
    Misc: 1
    Inflammatory: 2
    Epithelial: 3
    Spindle': 4

  data_ext: '.npy'
  train_dir:
    - '/data/output/extract/hv_seg_consep_540x540_80x80/train/Labels/'
  valid_dir:
    - '/data/output/extract/hv_seg_consep_540x540_80x80/test/Labels/'
  nr_procs_train: 8
  nr_procs_valid: 4
  input_norm: True

  inf_auto_find_chkpt: False
  inf_model_path: '/pfs/weights/weights_hv_seg_class_CoNSeP.npz'
  inf_imgs_ext: '.png'
  inf_data_list:
    - '/pfs/input/'
  
  remap_labels: False
