hv_consep:
  data_dir: data_hv_consep/data/
  data_modes:
  - train
  - test
  exp_id: '1.0'
  extract_type: mirror
  include_export: true
  include_extract: true
  include_preproc: true
  inf_auto_find_chkpt: true
  inf_data_list:
  - data_hv_consep/data/test/Images/
  input_augs: p_linear_plus
  input_norm: true
  input_prefix: /data/input/
  mode: hover
  model_type: np_hv
  nuclei_types:
    Epithelial: 3
    Inflammatory: 2
    Misc: 1
    Spindle: 4
  outline: ''
  output_prefix: /data/output/
  remap_labels: true
  seed: 10
  stain_norm:
    image: train_1
    mode: train
    norm_brightness: true
  step_size:
  - 80
  - 80
  train_dir:
  - train/Annotations
  type_classification: true
  valid_dir:
  - valid/Annotations
  win_size:
  - 540
  - 540
